### ISSUE TITLE
Issue when extracting release 0.0.2

### ISSUE THREAD

**Issue by BoatsAreRockable** [BiMStop/Biscuit#7]
When I try and extract the compressed ZIP folder of release 0.0.2 the following error occurs:
![Issue](http://i.imgur.com/7nxKZ8M.jpg)
Clicking "skip" allows the extraction process to finish but after opening Biscuit.exe and navigating to the capture page a video feed does not appear.

**Comment by lunears** [comment]
Is this a 32 bit or 64 bit installation?

**Comment by BoatsAreRockable** [comment]
The problem occurs with both

**Comment by BoatsAreRockable** [comment]
(Natively my computer is 64 bit though)

**Comment by lunears** [comment]
I see that the problem happens because of the node_module, the folder is too deep for windows to process.  
Place the unzipped file in Biscuit-win-x64/resources/app/node_modules/node-base64-image/node_modules/request/node_modules/ replacing hat-validator
https://raw.githubusercontent.com/BiMStop/Biscuit/master/har-validator.zip

**Comment by BoatsAreRockable** [comment]
I still have the same issue after the har-validator fix :(

**Comment by le717** [comment]
> This issue will no longer happen when we are using installers.

Unless you plan on changing the file path, an installer will only make it worse, as the files will be installed and you will never be able to delete them because of the error.

A better idea is to copy the scripts your app directly needs out the `node_modules/whatever` folder into a different folder (say `lib/`), load them from there, and never commit into Git and package the `node_modules` folder at all.

**Comment by lunears** [comment]
Replace node_modules in Biscuit-win-x64/resources/app/node_modules/node-base64-image/node_modules/request/ with https://raw.githubusercontent.com/BiMStop/Biscuit/master/fixes/node_modules.zip

**Comment by le717** [comment]
> With installers there won't be any unzipping.

I do not think you quite understand me. Let me try to explain this in a way you will understand, and keep in mind I have written many installers and did an informal case study on installers, including how they work, among other aspects, am a web developer, and have dealt with these exact things many times, always studying them, their causes, affects, and remedies.

On a fundamental level, there is no difference between a zip archive and an installer. Both compress files using complicated algorithms in order to make the files easier to share and transport. Some installers even use the .zip format compression scheme. Extracting an archive and running an installer are synonyms and specialized jargon for the exact same process, namely: using a different algorithm, decompress the files and perform OS write calls to copy the decompressed files to the chosen destination.

Fundamentally, both archives and installers are the exact same thing. The only difference is installers contain executable code to show its own UI, run other commands, and decompress the files automatically, something which "plain" archives can get too (ever heard of a self-extracting archive?).

You know how citizens of a city, state, or country must abide by the laws of the land? And you know how some places have laws that are different or do not exist in another place? Operating systems follow this same system. All OSs have different laws that programs for the respective platform must obey.

On Windows, one of those laws says that file and folder names combined must not exceed 255 characters. If they do, they cannot be deleted. Now technically, this law can be legally broken and longer names allowed, but that is for very special cases. Mac OS X and Linux do not have this law, only Windows. Normally, safeguards in Windows prevent us from breaking the law, but unfortunately it is not present everywhere and third-party applications can illegally break the law all day long.

One such habitual offender is npm, which creates the node_modules folder. You see, for any library that has dependencies, npm stores them in node_modules. However, all dependencies can have any number of dependencies, and npm always downloads those too. Very early on you will have a huge number of node_modules folders on your computer containing lots of dependencies. This can quickly break Windows' file path law because the OS safeguards do not affect npm. (For the record, the eventual npm 3.0.0 release will respect the law.)

What is going on in this issue is the `node-base64-images` module from npm Biscuit is using has many dependencies and sub-dependencies, and it is violating Windows' law. Because of the OS safeguards, you are not allowed to extract the zip archive and render the files unremovable.

However, an installer from anyone will not be affected by the safeguards and will merrily install everything, even if it breaks the law in doing so. So while this error would not occur with an installer, you will have made things worse by making them unremovable (because that applies at all times to everything).

The only way to truly fix this is
1. (Recommended and possibly easiest) Use a different method to save files to the computer. I'd suggest checking the documentation on the `fs` module and look for a file writer API.
2. Find a different library to save the files that lacks so many sub-dependencies.
3. Find a way to flatten the many sub-dependencies into a single file or folder, one _not_ inside the node_modules folder (I like using lib), load it from there, and remove node_modules from both Git and the released builds.

Hopefully this all makes sense to you now. :)

**Comment by lunears** [comment]
I just extracted release 0.1.0 with windows and had no errors, I'm not sure what would be causing your problems.

**Comment by lunears** [comment]
Issue fixed in release 0.2.1.
